# Generated by Django 5.0.4 on 2025-02-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tovar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tavsif', models.CharField(max_length=100)),
                ('imgs', models.ImageField(upload_to='images/')),
                ('sharhi', models.IntegerField(default=0)),
                ('asil_narx', models.IntegerField(default=0)),
                ('skidkasi', models.IntegerField(default=0)),
                ('foizi', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Tovar',
        ),
    ]
