# Generated by Django 5.0.4 on 2025-02-27 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tovar', '0002_tovars_delete_tovar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovars',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
