# Generated by Django 5.1.5 on 2025-03-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tovar', '0003_alter_tovars_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tovars',
        ),
    ]
